# Generated by Django 4.0.4 on 2022-09-09 08:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=200, verbose_name='Блюдо')),
                ('type', models.CharField(choices=[('drink', 'напиток'), ('second', 'второе'), ('soup', 'суп'), ('cream', 'запеканка'), ('salad', 'салат')], max_length=200, verbose_name='Тип блюда')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200, unique=True, verbose_name='Товар')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 0)], verbose_name='Цена')),
                ('deployer', models.CharField(max_length=200, verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('product',),
            },
        ),
        migrations.CreateModel(
            name='ProductsInDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 0)], verbose_name='Кол-во')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kitchen.dish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kitchen.product')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=200, unique=True, verbose_name='Меню')),
                ('dishes', models.ManyToManyField(to='kitchen.dish')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='products',
            field=models.ManyToManyField(through='kitchen.ProductsInDishes', to='kitchen.product'),
        ),
    ]
