# Generated by Django 4.0.4 on 2022-09-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish',
            field=models.CharField(max_length=200, unique=True, verbose_name='Блюдо'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.CharField(max_length=200, verbose_name='Тип блюда'),
        ),
    ]
